// src/utils/data.ts

export const SERVICES = [
  { id: 's1', name: 'Shirt Ironing', price: 25, unit: '/piece', icon: '👔', color: '#e8f4fd' },
  { id: 's2', name: 'Trouser Iron', price: 30, unit: '/piece', icon: '👖', color: '#f0e8fd' },
  { id: 's3', name: 'Suit Dry Clean', price: 350, unit: '/set', icon: '🧥', color: '#fdf0e8' },
  { id: 's4', name: 'Saree DC', price: 200, unit: '/piece', icon: '👗', color: '#fde8f4' },
  { id: 's5', name: 'Bedsheet Wash', price: 80, unit: '/piece', icon: '🛏️', color: '#e8fdf0' },
  { id: 's6', name: 'Curtain Wash', price: 120, unit: '/panel', icon: '🎭', color: '#fdf5e8' },
  { id: 's7', name: 'Gym Wear', price: 60, unit: '/piece', icon: '🏋️', color: '#e8fdfd' },
  { id: 's8', name: 'Soft Toy Clean', price: 150, unit: '/piece', icon: '🧸', color: '#fde8e8' },
  { id: 's9', name: 'Blanket Wash', price: 200, unit: '/piece', icon: '🛋️', color: '#f4fde8' },
  { id: 's10', name: 'Jacket DC', price: 180, unit: '/piece', icon: '🧤', color: '#e8eafd' },
];

export const SHOPS = [
  {
    id: 'sh1',
    name: 'Prestige Dry Cleaners',
    area: 'MP Nagar Zone 2',
    address: 'Shop 12, Zone 2 Market, MP Nagar',
    distance: 0.8,
    rating: 4.9,
    reviews: 248,
    isOpen: true,
    openTime: '09:00',
    closeTime: '21:00',
    isExpress: true,
    emoji: '🏆',
    bgColor: '#0d2a2a',
    prices: { 'Shirt': 25, 'Suit DC': 350, 'Saree': 200, 'Trouser': 30 },
    tags: ['Express', 'Top Rated', 'Verified'],
  },
  {
    id: 'sh2',
    name: 'Royal Laundry Palace',
    area: 'Arera Colony E-5',
    address: 'E-5/22, Near Axis Bank, Arera Colony',
    distance: 1.4,
    rating: 4.7,
    reviews: 184,
    isOpen: true,
    openTime: '08:00',
    closeTime: '22:00',
    isExpress: true,
    emoji: '👑',
    bgColor: '#1a1a2e',
    prices: { 'Shirt': 22, 'Suit DC': 320, 'Saree': 180, 'Trouser': 28 },
    tags: ['Express', 'Open Late'],
  },
  {
    id: 'sh3',
    name: 'CleanKing Bhopal',
    area: 'New Market',
    address: '45, New Market Road, Bhopal',
    distance: 2.1,
    rating: 4.5,
    reviews: 312,
    isOpen: true,
    openTime: '09:00',
    closeTime: '20:00',
    isExpress: false,
    emoji: '🧺',
    bgColor: '#0d1117',
    prices: { 'Shirt': 20, 'Suit DC': 300, 'Saree': 160, 'Trouser': 25 },
    tags: ['Budget Friendly'],
  },
  {
    id: 'sh4',
    name: 'Sharma Tailors & Cleaners',
    area: 'Shahpura',
    address: 'Near Shahpura Lake, Bhopal',
    distance: 2.8,
    rating: 4.6,
    reviews: 97,
    isOpen: false,
    openTime: '10:00',
    closeTime: '19:00',
    isExpress: false,
    emoji: '✂️',
    bgColor: '#2a1a0d',
    prices: { 'Shirt': 18, 'Suit DC': 280, 'Saree': 150, 'Trouser': 22 },
    tags: ['Tailoring Available'],
  },
  {
    id: 'sh5',
    name: 'FabFresh Dry Clean',
    area: 'BHEL Sector C',
    address: 'Sector C Main Road, BHEL Bhopal',
    distance: 3.2,
    rating: 4.8,
    reviews: 156,
    isOpen: true,
    openTime: '09:00',
    closeTime: '21:00',
    isExpress: true,
    emoji: '✨',
    bgColor: '#0a2a1a',
    prices: { 'Shirt': 28, 'Suit DC': 380, 'Saree': 220, 'Trouser': 35 },
    tags: ['Express', 'Premium'],
  },
  {
    id: 'sh6',
    name: 'ShineBright Cleaners',
    area: 'Kolar Road',
    address: 'Kolar Road, Near DPS School',
    distance: 5.0,
    rating: 4.7,
    reviews: 121,
    isOpen: true,
    openTime: '09:00',
    closeTime: '21:00',
    isExpress: true,
    emoji: '⭐',
    bgColor: '#1a1020',
    prices: { 'Shirt': 30, 'Suit DC': 400, 'Saree': 240, 'Trouser': 38 },
    tags: ['Express', 'Premium', 'Verified'],
  },
];

export const AREAS = [
  'MP Nagar', 'Arera Colony', 'Kolar Road', 'Shahpura',
  'New Market', 'BHEL', 'Govindpura', 'TT Nagar', 'Kohefiza', 'Lalghati',
];

export const ORDER_STATUSES = {
  pending: { label: 'Order Placed', color: '#c8a84b', icon: '📋' },
  assigned: { label: 'Agent Assigned', color: '#14766e', icon: '👤' },
  picked_up: { label: 'Clothes Picked Up', color: '#14766e', icon: '📦' },
  processing: { label: 'At Shop — Cleaning', color: '#1da096', icon: '🧺' },
  ready: { label: 'Ready for Delivery', color: '#28764a', icon: '✅' },
  out_for_delivery: { label: 'Out for Delivery', color: '#c8a84b', icon: '🚗' },
  delivered: { label: 'Delivered', color: '#28764a', icon: '🎉' },
};
